### ISSUE TITLE
Files aren't uploading after Rails 6 upgrade

### ISSUE THREAD

**Issue by webaholik** [itsprdp/gcloud_storage#8]
Are there any known issues using this gem with Rails 6?

We started using `gcloud_storage` while on Rails 4. Everything was working great. We recently updated to Rails 6 noticed that files are no longer uploading. I may swap this over to use ActiveStorage instead (which we did start using for other models), but I was hoping `gcloud_storage` would continue to work as-is.

I'm able to go through the entire "File upload example" in rails console, creating a text file and saving it. No errors, but no indication that the file is uploaded to my cloud bucket either. The error comes when trying `temp_file.file_url` - 404 not found.

**Comment by itsprdp** [comment]
@webaholik, I haven't checked with Rails 6 yet. Most likely the `gcloud` gem's latest version might have changed. Let me take a look at it and see if I can fix the issue.

**Comment by itsprdp** [comment]
@webaholik could you help me with the `ruby` and the `rails` gem versions that you're using?

**Comment by webaholik** [comment]
ruby 2.6.4
Rails 6.0.0

**Comment by itsprdp** [comment]
@webaholik confirming that I could reproduce this issue on my end for `ruby 2.6.4`.

**Comment by webaholik** [comment]
@itsprdp - thanks for confirming, glad to know it's not just me!

**Comment by itsprdp** [comment]
@webaholik  Due to changes around `after_save` the ActiveRecord::Dirty methods `changed?` and `<field>_changed?` behaves differently from  `v5.0` and above for `ActiveRecord`.

I have published the new version and the issue should be resolved now. https://rubygems.org/gems/gcloud_storage/versions/0.0.5

Thanks!

**Comment by webaholik** [comment]
@itsprdp - that seems to have fixed the issue, thanks so much for your promptness!
